### ISSUE TITLE
Provisioning fails with "Waiting for shoot condition to finish" error message

### ISSUE THREAD

**Issue by akgalwas** [kyma-incubator/hydroform#60] opened 2020-01-07 15:37 UTC
**Description**

While performing tests on Compass Provisioner component (Azure on Gardener) I noticed the following error returned from Hydroform: "Waiting for shoot condition to finish: ControlPlaneHealthy" occurring once in a while (4 out of 12 runs). After checking Gardener project it turned out that cluster has been provisioned so that the state stored by Provisioner is inconsistent.

**Expected result**

Hydroform provides blocking, synchronous operations. Provision method call shouldn't finish before Gardener completed cluster provisioning. It may be a matter of incorrect handling of Gardener Shoot resource statuses.

**Actual result**

Provision method fails with error but Gardener keeps retrying cluster creation. 

**Steps to reproduce**

The issue is random. The issue is random. The following setting were used for provisioning:
```
"clusterConfig": {
                    "name": "<name>",
                    "projectName": "<project_name>",
                    "kubernetesVersion": "1.15.4",
                    "nodeCount": 3,
                    "volumeSizeGB": 35,
                    "machineType": "Standard_D2_v3",
                    "region": "westeurope",
                    "provider": "azure",
                    "seed": "az-eu1",
                    "targetSecret": "<target secret>",
                    "diskType": "Standard_LRS",
                    "workerCidr": "10.250.0.0/19",
                    "autoScalerMin": 2,
                    "autoScalerMax": 4,
                    "maxSurge": 4,
                    "maxUnavailable": 1,
                    "providerSpecificConfig": {
                        "vnetCidr": "10.250.0.0/19"
                    }
                }
```

**Comment by akgalwas** [comment] 2020-01-08 09:56
One additional info: Provisioner sets up 40 minutes timeout for Hydroform. The issue may be a result of Gardener problem, but looking at the code it seems that ConditionProgressing error is recoverable. Looking at the error message it is not sure if there was a Terraform timeout (which can be a case) or Gardener Shoot resource state handling is incorrect.

**Comment by a-thaler** [comment] 2020-01-13 12:21
We will try to address it by https://github.com/kyma-incubator/hydroform/issues/58 by having a way of syncing the remote state and supporting a re-try.

**Comment by clebs** [comment] 2020-01-22 09:14
This issue in particular is caused by how gardener manages errors in created resources and retries.

The reattach/recover/sync mechanisms built in #58 will allow to overcome this problem.

Closing this issue.

**Closed by clebs** 2020-01-22 09:14 UTC
Labels: area/cli, bug
