### ISSUE TITLE
Hydroform finishes cluster provisioning without an error when cluster is not yet provisioned

### ISSUE THREAD

**Issue by Szymongib** [kyma-incubator/hydroform#48] opened 2019-12-02 14:02 UTC
**Description**

While provisioning Gardener cluster on Azure I encountered an issue that the `Provision` method returned without an error and the cluster status after running `Status` was equal to `Provisioned`, yet the cluster was not yet provisioned and `Credentials` function returned an error `secrets \"{CLUSTER_NAME}.kubeconfig\" not found.`
I observed that similar behavior happens sometimes on `Deprovision` operation.

**Expected result**

`Provision` method returns only if the cluster is properly provisioned or when an error occurred.

**Actual result**

`Provision` method returns without an error and the cluster status returned from Hydrofrom is equal to `Provisioned`, even though the cluster is still provisioning.

**Comment by clebs** [comment] 2019-12-06 10:12
This is a duplicate of #41, closing.

**Closed by clebs** 2019-12-06 10:12 UTC
Labels: bug
